messager with types of messages - msg, login
alexandragushchina-d/messager pull request #1
Opened 2020-09-09 22:52 UTC by alexandragushchina-d

2020-09-09 22:54 UTC, alexandragushchina-d commented
A echo server for several users using telnet to send messages with type "msg", "login"

2020-09-09 22:56 UTC, VladislavHacker commented on src/Main.java
> +    Server server = new Server("localhost",9090);
Пробел после ,

2020-09-09 22:57 UTC, VladislavHacker commented on src/Main.java
> +  public static void main(String[] args) throws IOException {
main пробел

2020-09-09 23:07 UTC, VladislavHacker requested changes

2020-09-09 23:07 UTC, VTroyanGolovyan commented on src/MyThread.java
> +  private void processUserInput(DataInputStream dis, DataOutputStream dos) throws IOException {
опять пробелы - везде их проверь

2020-09-09 23:07 UTC, VladislavHacker commented on src/MyThread.java
> +  private void checkLogin(String[] data) throws FileNotFoundException {
синхронизировать кто будет?

2020-09-09 23:07 UTC, VladislavHacker commented on src/Server.java
> +public class Server {
перенос строки - чтобы код было читать приятнее

2020-09-09 23:07 UTC, VladislavHacker commented on src/Server.java
> +  public Server() {
??? и что он делает? Может нужно проинициализировать значения по умолчанию?

2020-09-09 23:07 UTC, VladislavHacker commented on src/Server.java
> +      MyThread myThread = new MyThread(users, socket);
new MyThread(users, socket).start() - так короче

2020-09-09 23:07 UTC, VladislavHacker commented on src/Server.java
> +  private int port = 8080;
Зачем делать это тут если ты создала конструктор Server() где можно заполнить все поля по умолчанию

2020-09-09 23:07 UTC, VladislavHacker commented on src/MyThread.java
> +        userName = data[0];
Было бы хорошо использовать this там где ты используешь свойства класса - так проще понять какие переменные являются полями класса, а какие - нет

2020-09-11 20:29 UTC, VladislavHacker approved these changes

2020-09-11 20:29 UTC, merged